export const runtime = "nodejs";

const schema = {
  version: "MG-AIOS v4",
  principle: "Case first. ChatGPT handles thinking. MG-AIOS is the AI Workspace, system of record, and workflow center.",
  priorityFormula: "dealValue * probability * urgency * overdueDays",
  models: {
    Case: [
      "propertyId",
      "caseRole",
      "caseType",
      "currentStage",
      "nextStep",
      "reminderDate",
      "sourceContentHash",
      "journeyIds",
      "eventIds",
      "taskIds",
      "fileIds",
      "financialIds",
      "aiSummary",
      "aiInsight",
      "aiBrain",
      "notes",
    ],
    ChatGptImport: [
      "contact",
      "property",
      "caseTitle",
      "caseType",
      "caseRole",
      "summary",
      "insight",
      "stage",
      "nextStep",
      "reminderDate",
      "finalContent",
      "sourceHash",
    ],
    Property: [
      "ownerContactIds",
      "buyerContactIds",
      "tenantContactIds",
      "repairIds",
      "journeyIds",
      "fileIds",
      "financialIds",
      "aiAnalysis",
    ],
    Contact: ["roles", "phone", "line", "email", "job", "birthday", "tags", "aiSummary"],
    Journey: [
      "type",
      "stage",
      "nextAction",
      "probability",
      "aiSuggestion",
      "reminderDate",
      "completedRecords",
      "history",
    ],
    Event: [
      "caseId",
      "eventType",
      "title",
      "description",
      "eventDate",
      "startTime",
      "endTime",
      "status",
      "priority",
      "source",
      "aiResponseHash",
      "googleCalendarEventId",
    ],
    PromptBuilder: [
      "caseContext",
      "promptTemplate",
      "finalPrompt",
      "copyToClipboard",
      "openChatGPT",
      "openClaude",
      "openGemini",
    ],
    Repair: [
      "propertyId",
      "issue",
      "photoUrls",
      "videoUrls",
      "status",
      "quote",
      "scheduledDate",
      "completedDate",
      "warranty",
      "vendor",
      "cost",
      "aiReminder",
    ],
    AiCenter: [
      "summarize",
      "rankTopFive",
      "generateLineMessage",
      "generateFollowUpSuggestion",
      "predictDealProbability",
      "detectRisk",
    ],
  },
};

export async function GET() {
  return new Response(JSON.stringify(schema, null, 2), {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}
